version: '1.0'
services:
  node-app:
    container_name: node-app
    restart: unless-stopped
    build:
      context: ./

  caddy:
    image: caddy/caddy:latest-alpine
    container_name: caddy-service
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:            
    - $PWD/Caddyfile:/etc/caddy/Caddyfile
    - $PWD/site:/srv
    - caddy_data:/data
    - caddy_config:/config

volumes:
  caddy_data:
  caddy_config:
